=== nkerft/L2_Way/Server Build - Web/L2J_Mobius_12.3_Superion/game/data/scripts/events/CrossEvent/CrossEvent.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence minOccurs="1" maxOccurs="1">
				<xs:element name="displayId" minOccurs="1" maxOccurs="1" />
				<xs:element name="ticketId" minOccurs="1" maxOccurs="1" />
				<xs:element name="dailyResets" minOccurs="1" maxOccurs="1" />
				<xs:element name="dailyResetsCostAmount" minOccurs="1" maxOccurs="1" />
				<xs:element name="cells" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="cell" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="rewardId" type="xs:positiveInteger" use="required" />
									<xs:attribute name="rewardAmount" type="xs:positiveInteger" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="advancedRewards" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence minOccurs="1" maxOccurs="1">
							<xs:element name="item" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:attribute name="id" type="xs:positiveInteger" use="required" />
									<xs:attribute name="count" type="xs:positiveInteger" use="optional" />
									<xs:attribute name="chance" type="xs:double" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nkerft/L2_Way/Server Build - Web/L2J_Mobius_12.3_Superion/game/data/scripts/events/CrossEvent/CrossEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CrossEvent.xsd">
	<displayId>1</displayId> <!-- 0 Normal, 1 Summer, 4 Winter -->
	<ticketId>60833</ticketId> <!-- Summer Flower Coupon -->
	<dailyResets>3</dailyResets>
	<dailyResetsCostAmount>10000000</dailyResetsCostAmount>
	<cells>
		<cell id="1" rewardId="82305" rewardAmount="100" /> <!-- Beora's Ancient Energy -->
		<cell id="2" rewardId="82345" rewardAmount="30" /> <!-- Tales of Aden - Event -->
		<cell id="3" rewardId="82280" rewardAmount="5" /> <!-- Supply Support Pack -->
		<cell id="4" rewardId="80906" rewardAmount="2" /> <!-- Jamoa's Camp's Time Stone - Event -->
		<cell id="5" rewardId="80905" rewardAmount="2" /> <!-- Fioren's Crystal Prison's Time Stone - Event -->
		<cell id="6" rewardId="81815" rewardAmount="1" /> <!-- Common Homunculus' Hourglass -->
		<cell id="7" rewardId="82305" rewardAmount="50" /> <!-- Beora's Ancient Energy -->
		<cell id="8" rewardId="80960" rewardAmount="1" /> <!-- Pantheon's Museum's Time Stone - Event -->
		<cell id="9" rewardId="13302" rewardAmount="10" /> <!-- My Teleport Scroll - Event -->
		<cell id="10" rewardId="83007" rewardAmount="3" /> <!-- Relic Summon Coupon - 1-time -->
		<cell id="11" rewardId="82658" rewardAmount="5" /> <!-- Sealed Fire Source -->
		<cell id="12" rewardId="82280" rewardAmount="10" /> <!-- Supply Support Pack -->
		<cell id="13" rewardId="81812" rewardAmount="1" /> <!-- Homunculus Upgrade Points - 10 -->
		<cell id="14" rewardId="81887" rewardAmount="1" /> <!-- Rune Stone -->
		<cell id="15" rewardId="81215" rewardAmount="30" /> <!-- Aether -->
		<cell id="16" rewardId="81708" rewardAmount="20" /> <!-- Scroll: Festival Fairy's Spring Energy - Event -->
	</cells>
	<advancedRewards>
		<item id="82766" count="1" chance="10.00" /> <!-- Golden Orb - Event -->
		<item id="82356" count="1" chance="8.00" /> <!-- Enhanced Rune Stone -->
		<item id="39572" count="1" chance="6.00" /> <!-- Talisman of Insanity -->
		<item id="37717" count="1" chance="4.00" /> <!-- Talisman of Seven Signs -->
		<item id="82904" count="1" chance="3.00" /> <!-- Homunculus' Shiny Hourglass -->
		<item id="83006" count="1" chance="2.25" /> <!-- Relic Summon Coupon - 11-time -->
		<item id="82305" count="200" chance="1.50" /> <!-- Beora's Ancient Energy -->
		<item id="48848" count="30" chance="12.00" /> <!-- Freya's Ice Rose - Event -->
		<item id="81013" count="30" chance="15.00" /> <!-- Nevit's Shining Gold Hourglass - Event -->
		<item id="81011" count="30" chance="20.00" /> <!-- Honey Dark Beer - Event -->
		<item id="48857" count="30" chance="25.00" /> <!-- Glowing Dragon's Attribute Potion (XP) - Event -->
		<item id="81012" count="15" chance="30.00" /> <!-- Emperor's Special Cocktail - Event -->
		<item id="83025" count="30" chance="35.00" /> <!-- Royal Santiago's Soup - Event -->
		<item id="81708" count="50" chance="40.00" /> <!-- Scroll: Festival Fairy's Spring Energy - Event -->
	</advancedRewards>
</list>

=== nkerft/L2_Way/Server Build - Web/L2J_Mobius_12.3_Superion/game/data/CrossEvent.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd/CrossEvent.xsd">
	<dailyResets>5</dailyResets>
    <cells>
 		<cell id="1" rewardId="100722" rewardAmount="1" /> <!-- Dye Hardener - Imprint -->
 		<cell id="2" rewardId="99043" rewardAmount="10" /> <!-- Golden Fruit Buff Lv. 3 - Imprint -->
 		<cell id="3" rewardId="99044" rewardAmount="10" /> <!-- Dragon's Special Elixir Lv. 3 - Imprint -->
 		<cell id="4" rewardId="91938" rewardAmount="1" /> <!-- Primeval Isle Time Recharge Stone -->
 		<cell id="5" rewardId="91939" rewardAmount="1" /> <!-- Tomb of Ancient Pirates Time Recharge Stone -->
 		<cell id="6" rewardId="90794" rewardAmount="10" /> <!-- Shining Scroll of Mood Melody - Imprint -->
 		<cell id="7" rewardId="90183" rewardAmount="10" /> <!-- Chef's Fish Stew - Victory -->
 		<cell id="8" rewardId="90907" rewardAmount="100" /> <!-- Soulshot Ticket - Imprint -->
 		<cell id="9" rewardId="49674" rewardAmount="10" /> <!-- XP Boost Scroll - Imprint -->
 		<cell id="10" rewardId="100812" rewardAmount="1" /> <!-- Doll Summoning Ticket (Regular-Top-grade) - 11 Times - Imprint -->
 		<cell id="11" rewardId="97147" rewardAmount="5" /> <!-- Potential Hardener - Imprint -->
 		<cell id="12" rewardId="57" rewardAmount="10000000" /> <!-- 10.000.000 Adena -->
 		<cell id="13" rewardId="96030" rewardAmount="5" /> <!-- Sayha's Storm Lv. 4 - Imprint -->
 		<cell id="14" rewardId="91741" rewardAmount="5" /> <!-- Einhasad's Protection - Imprint -->
 		<cell id="15" rewardId="57" rewardAmount="1" /> <!--  -->
 		<cell id="16" rewardId="57" rewardAmount="1" /> <!--  -->
    </cells>
    <advancedRewards>
                <item id="90831" count="1" /> <!-- Transformation Scroll: White Assassin -->
                <item id="99016" count="1" /> <!-- Golden Fruit Buff Lv. 2 (Time-limited) -->
    </advancedRewards>
</list>
