=== nkerft/L2_Way/Server Build - Web/L2J_Mobius_12.3_Superion/game/data/scripts/events/SecretShop/SecretShop.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:int" name="ticketId" />
				<xs:element type="xs:string" name="startTime" />
				<xs:element type="xs:string" name="endTime" />
				<xs:element name="rewards" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="item" maxOccurs="unbounded" minOccurs="0">
								 <xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:int" name="id" use="optional" />
											<xs:attribute type="xs:byte" name="grade" use="optional" />
											<xs:attribute type="xs:short" name="count" use="optional" />
											<xs:attribute type="xs:short" name="totalAmount" use="optional" />
											<xs:attribute type="xs:float" name="chance" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:byte" name="day" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nkerft/L2_Way/Server Build - Web/L2J_Mobius_12.3_Superion/game/data/scripts/events/SecretShop/SecretShop.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="SecretShop.xsd">
	<ticketId>82073</ticketId> <!-- Iron Gate's Key -->
	<startTime>8:00</startTime>
	<endTime>20:00</endTime>
	<rewards day="1">
		<!-- Three Star -->
		<item id="98044" grade="1" count="1" totalAmount="1" chance="0.2" /> <!-- +5 Special Armor Coupon (Time-limited) Sealed -->
		<item id="97797" grade="1" count="3" totalAmount="1" chance="0.15" /> <!-- Package: Talisman of Authority (100 pcs.) Sealed -->
		<item id="98335" grade="1" count="4" totalAmount="1" chance="0.1" /> <!-- Package: Augmenting Stone: Armor (50 pcs.) (Time-limited) Sealed -->
		
		<!-- Two Star -->
		<item id="97641" grade="2" count="100" totalAmount="1500" chance="2" /> <!-- Package: Secret Shop Coin (100 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="200" totalAmount="1200" chance="1.5" /> <!-- Package: Secret Shop Coin (200 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="5000" totalAmount="1000" chance="1" /> <!-- Package: Secret Shop Coin (500 pcs.) (Time-limited) Sealed -->
		<item id="94780" grade="2" count="20" totalAmount="500" chance="1.2" /> <!-- Growth Rune Fragment Sealed -->
		<item id="98917" grade="2" count="1" totalAmount="500" chance="1" /> <!-- Talisman Coupon (Time-limited) Sealed -->
		<item id="97284" grade="2" count="1" totalAmount="10" chance="0.8" /> <!-- Common Doll Summon Coupon Pack Sealed -->
		
		<!-- One Star -->
		<item id="97640" grade="3" count="1" totalAmount="25000" chance="10" /> <!-- Secret Shop Coin (Time-limited) Sealed -->
		<item id="98916" grade="3" count="5" totalAmount="12000" chance="8" /> <!-- Package: Secret Shop Coin (5 pcs.) (Time-limited) Sealed -->
		<item id="98915" grade="3" count="10" totalAmount="10000" chance="8" /> <!-- Package: Secret Shop Coin (10 pcs.) (Time-limited) Sealed -->
		<item id="94838" grade="3" count="5" totalAmount="3000" chance="7" /> <!-- Transformation Scroll (Time-limited) Sealed -->
		<item id="94271" grade="3" count="5" totalAmount="5000" chance="6" /> <!-- Scroll: Boost Defense (Time-limited) Sealed -->
		<item id="94269" grade="3" count="5" totalAmount="5000" chance="6" /> <!-- Scroll: Boost Attack (Time-limited) Sealed -->
	</rewards>
	<rewards day="2">
		<!-- Three Star -->
		<item id="98044" grade="1" count="1" totalAmount="1" chance="0.2" /> <!-- +5 Special Armor Coupon (Time-limited) Sealed -->
		<item id="97797" grade="1" count="3" totalAmount="1" chance="0.15" /> <!-- Package: Talisman of Authority (100 pcs.) Sealed -->
		<item id="98335" grade="1" count="4" totalAmount="1" chance="0.1" /> <!-- Package: Augmenting Stone: Armor (50 pcs.) (Time-limited) Sealed -->
		
		<!-- Two Star -->
		<item id="97641" grade="2" count="100" totalAmount="1500" chance="2" /> <!-- Package: Secret Shop Coin (100 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="200" totalAmount="1200" chance="1.5" /> <!-- Package: Secret Shop Coin (200 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="5000" totalAmount="1000" chance="1" /> <!-- Package: Secret Shop Coin (500 pcs.) (Time-limited) Sealed -->
		<item id="94780" grade="2" count="20" totalAmount="500" chance="1.2" /> <!-- Growth Rune Fragment Sealed -->
		<item id="98917" grade="2" count="1" totalAmount="500" chance="1" /> <!-- Talisman Coupon (Time-limited) Sealed -->
		<item id="97284" grade="2" count="1" totalAmount="10" chance="0.8" /> <!-- Common Doll Summon Coupon Pack Sealed -->
		
		<!-- One Star -->
		<item id="97640" grade="3" count="1" totalAmount="25000" chance="10" /> <!-- Secret Shop Coin (Time-limited) Sealed -->
		<item id="98916" grade="3" count="5" totalAmount="12000" chance="8" /> <!-- Package: Secret Shop Coin (5 pcs.) (Time-limited) Sealed -->
		<item id="98915" grade="3" count="10" totalAmount="10000" chance="8" /> <!-- Package: Secret Shop Coin (10 pcs.) (Time-limited) Sealed -->
		<item id="94838" grade="3" count="5" totalAmount="3000" chance="7" /> <!-- Transformation Scroll (Time-limited) Sealed -->
		<item id="94271" grade="3" count="5" totalAmount="5000" chance="6" /> <!-- Scroll: Boost Defense (Time-limited) Sealed -->
		<item id="94269" grade="3" count="5" totalAmount="5000" chance="6" /> <!-- Scroll: Boost Attack (Time-limited) Sealed -->
	</rewards>
	<rewards day="3">
		<!-- Three Star -->
		<item id="98044" grade="1" count="1" totalAmount="1" chance="0.2" /> <!-- +5 Special Armor Coupon (Time-limited) Sealed -->
		<item id="97797" grade="1" count="3" totalAmount="1" chance="0.15" /> <!-- Package: Talisman of Authority (100 pcs.) Sealed -->
		<item id="98335" grade="1" count="4" totalAmount="1" chance="0.1" /> <!-- Package: Augmenting Stone: Armor (50 pcs.) (Time-limited) Sealed -->
		
		<!-- Two Star -->
		<item id="97641" grade="2" count="100" totalAmount="1500" chance="2" /> <!-- Package: Secret Shop Coin (100 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="200" totalAmount="1200" chance="1.5" /> <!-- Package: Secret Shop Coin (200 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="5000" totalAmount="1000" chance="1" /> <!-- Package: Secret Shop Coin (500 pcs.) (Time-limited) Sealed -->
		<item id="94780" grade="2" count="20" totalAmount="500" chance="1.2" /> <!-- Growth Rune Fragment Sealed -->
		<item id="98917" grade="2" count="1" totalAmount="500" chance="1" /> <!-- Talisman Coupon (Time-limited) Sealed -->
		<item id="97284" grade="2" count="1" totalAmount="10" chance="0.8" /> <!-- Common Doll Summon Coupon Pack Sealed -->
		
		<!-- One Star -->
		<item id="97640" grade="3" count="1" totalAmount="25000" chance="10" /> <!-- Secret Shop Coin (Time-limited) Sealed -->
		<item id="98916" grade="3" count="5" totalAmount="12000" chance="8" /> <!-- Package: Secret Shop Coin (5 pcs.) (Time-limited) Sealed -->
		<item id="98915" grade="3" count="10" totalAmount="10000" chance="8" /> <!-- Package: Secret Shop Coin (10 pcs.) (Time-limited) Sealed -->
		<item id="94838" grade="3" count="5" totalAmount="3000" chance="7" /> <!-- Transformation Scroll (Time-limited) Sealed -->
		<item id="94271" grade="3" count="5" totalAmount="5000" chance="6" /> <!-- Scroll: Boost Defense (Time-limited) Sealed -->
		<item id="94269" grade="3" count="5" totalAmount="5000" chance="6" /> <!-- Scroll: Boost Attack (Time-limited) Sealed -->
	</rewards>
	<rewards day="4">
		<!-- Three Star -->
		<item id="98044" grade="1" count="1" totalAmount="1" chance="0.2" /> <!-- +5 Special Armor Coupon (Time-limited) Sealed -->
		<item id="97797" grade="1" count="3" totalAmount="1" chance="0.15" /> <!-- Package: Talisman of Authority (100 pcs.) Sealed -->
		<item id="98335" grade="1" count="4" totalAmount="1" chance="0.1" /> <!-- Package: Augmenting Stone: Armor (50 pcs.) (Time-limited) Sealed -->
		
		<!-- Two Star -->
		<item id="97641" grade="2" count="100" totalAmount="1500" chance="2" /> <!-- Package: Secret Shop Coin (100 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="200" totalAmount="1200" chance="1.5" /> <!-- Package: Secret Shop Coin (200 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="5000" totalAmount="1000" chance="1" /> <!-- Package: Secret Shop Coin (500 pcs.) (Time-limited) Sealed -->
		<item id="94780" grade="2" count="20" totalAmount="500" chance="1.2" /> <!-- Growth Rune Fragment Sealed -->
		<item id="98917" grade="2" count="1" totalAmount="500" chance="1" /> <!-- Talisman Coupon (Time-limited) Sealed -->
		<item id="97284" grade="2" count="1" totalAmount="10" chance="0.8" /> <!-- Common Doll Summon Coupon Pack Sealed -->
		
		<!-- One Star -->
		<item id="97640" grade="3" count="1" totalAmount="25000" chance="10" /> <!-- Secret Shop Coin (Time-limited) Sealed -->
		<item id="98916" grade="3" count="5" totalAmount="12000" chance="8" /> <!-- Package: Secret Shop Coin (5 pcs.) (Time-limited) Sealed -->
		<item id="98915" grade="3" count="10" totalAmount="10000" chance="8" /> <!-- Package: Secret Shop Coin (10 pcs.) (Time-limited) Sealed -->
		<item id="94838" grade="3" count="5" totalAmount="3000" chance="7" /> <!-- Transformation Scroll (Time-limited) Sealed -->
		<item id="94271" grade="3" count="5" totalAmount="5000" chance="6" /> <!-- Scroll: Boost Defense (Time-limited) Sealed -->
		<item id="94269" grade="3" count="5" totalAmount="5000" chance="6" /> <!-- Scroll: Boost Attack (Time-limited) Sealed -->
	</rewards>
	<rewards day="5">
		<!-- Three Star -->
		<item id="98044" grade="1" count="1" totalAmount="1" chance="0.2" /> <!-- +5 Special Armor Coupon (Time-limited) Sealed -->
		<item id="97797" grade="1" count="3" totalAmount="1" chance="0.15" /> <!-- Package: Talisman of Authority (100 pcs.) Sealed -->
		<item id="98335" grade="1" count="4" totalAmount="1" chance="0.1" /> <!-- Package: Augmenting Stone: Armor (50 pcs.) (Time-limited) Sealed -->
		
		<!-- Two Star -->
		<item id="97641" grade="2" count="100" totalAmount="1500" chance="2" /> <!-- Package: Secret Shop Coin (100 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="200" totalAmount="1200" chance="1.5" /> <!-- Package: Secret Shop Coin (200 pcs.) (Time-limited) Sealed -->
		<item id="97642" grade="2" count="5000" totalAmount="1000" chance="1" /> <!-- Package: Secret Shop Coin (500 pcs.) (Time-limited) Sealed -->
		<item id="94780" grade="2" count="20" totalAmount="500" chance="1.2" /> <!-- Growth Rune Fragment Sealed -->
		<item id="98917" grade="2" count="1" totalAmount="500" chance="1" /> <!-- Talisman Coupon (Time-limited) Sealed -->
		<item id="97284" grade="2" count="1" totalAmount="10" chance="0.8" /> <!-- Common Doll Summon Coupon Pack Sealed -->
		
		<!-- One Star -->
		<item id="97640" grade="3" count="1" totalAmount="25000" chance="10" /> <!-- Secret Shop Coin (Time-limited) Sealed -->
		<item id="98916" grade="3" count="5" totalAmount="12000" chance="8" /> <!-- Package: Secret Shop Coin (5 pcs.) (Time-limited) Sealed -->
